on: repository_dispatch

name: Dr. Ian Malcolm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          for type in data domdom; do
            rm -rf "$type"
            git clone "https://github.com/eirikb/$type" "$type-source"
            cp "$type-source/LICENSE" ./

            cat .github/workflows/_README.md "$type-source/readme.md" > README.md

            mv "$type-source/src" "$type"
            rm -rf *-source

            sed -ri 's/global/window/' "$type"/*
            sed -ri "s/(from '.*)'.*/\1.ts';/" "$type"/*
          done

          sed -ri "s/from.*@eirikb.*/from '..\/data\/index.ts';/" domdom/*

          git config --global user.name 'Boten Anna'
          git config --global user.email 'eirikb@eirikb.no'
          git add .
          git commit -m 'Automatic!'
          git push origin master

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get latest domdom tag
        run: |
          export VERSION=$(git ls-remote --tags --refs --sort="v:refname" https://github.com/eirikb/domdom | tail -n1 | sed 's/.*\///')
          echo "VERSION is $VERSION"
          echo "VERSION=$(npm show . version)" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
